-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text, 'archived'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  display_name text,
  email text,
  avatar_url text,
  locale text NOT NULL DEFAULT 'ar'::text,
  timezone text NOT NULL DEFAULT 'Africa/Cairo'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.organization_members (
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['invited'::text, 'active'::text, 'suspended'::text, 'removed'::text])),
  joined_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (organization_id, user_id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  is_system boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.role_permissions (
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id),
  CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.permissions(id)
);
CREATE TABLE public.user_roles (
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (organization_id, user_id, role_id),
  CONSTRAINT user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.team_members (
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  is_lead boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_members_pkey PRIMARY KEY (team_id, user_id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.business_portfolios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  meta_business_id text NOT NULL,
  name text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'missing_from_meta'::text, 'requires_review'::text, 'archived'::text])),
  is_primary boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT business_portfolios_pkey PRIMARY KEY (id),
  CONSTRAINT business_portfolios_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.meta_apps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  business_portfolio_id uuid,
  meta_app_id text NOT NULL,
  display_name text NOT NULL,
  namespace text,
  app_domains ARRAY NOT NULL DEFAULT '{}'::text[],
  privacy_policy_url text,
  terms_url text,
  data_deletion_url text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'review'::text, 'restricted'::text, 'archived'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_apps_pkey PRIMARY KEY (id),
  CONSTRAINT meta_apps_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT meta_apps_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id)
);
CREATE TABLE public.wabas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  business_portfolio_id uuid NOT NULL,
  meta_waba_id text NOT NULL,
  name text,
  currency text,
  timezone text,
  account_review_status text,
  business_verification_status text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'missing_from_meta'::text, 'requires_review'::text, 'restricted'::text, 'archived'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wabas_pkey PRIMARY KEY (id),
  CONSTRAINT wabas_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT wabas_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id)
);
CREATE TABLE public.meta_app_wabas (
  meta_app_id uuid NOT NULL,
  waba_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'pending'::text, 'error'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_app_wabas_pkey PRIMARY KEY (meta_app_id, waba_id),
  CONSTRAINT meta_app_wabas_meta_app_id_fkey FOREIGN KEY (meta_app_id) REFERENCES public.meta_apps(id),
  CONSTRAINT meta_app_wabas_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id)
);
CREATE TABLE public.whatsapp_numbers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  waba_id uuid NOT NULL,
  meta_phone_number_id text NOT NULL,
  display_phone_number text,
  normalized_phone_number text,
  verified_name text,
  internal_name text,
  department text,
  country text,
  purpose text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  code_verification_status text,
  quality_rating text,
  platform_type text,
  throughput_level text,
  messaging_limit text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'missing_from_meta'::text, 'requires_review'::text, 'restricted'::text, 'disconnected'::text, 'archived'::text])),
  is_enabled boolean NOT NULL DEFAULT true,
  is_default boolean NOT NULL DEFAULT false,
  timezone text,
  default_language text DEFAULT 'ar'::text,
  webhook_status text,
  last_incoming_message_at timestamp with time zone,
  last_outgoing_message_at timestamp with time zone,
  last_api_success_at timestamp with time zone,
  last_api_failure_at timestamp with time zone,
  last_synced_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT whatsapp_numbers_pkey PRIMARY KEY (id),
  CONSTRAINT whatsapp_numbers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT whatsapp_numbers_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id)
);
CREATE TABLE public.meta_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  meta_app_id uuid,
  business_portfolio_id uuid,
  waba_id uuid,
  whatsapp_number_id uuid,
  credential_type text NOT NULL CHECK (credential_type = ANY (ARRAY['system_user_token'::text, 'user_token'::text, 'app_secret'::text, 'verify_token'::text, 'access_token'::text, 'other'::text])),
  name text NOT NULL,
  secret_reference text NOT NULL,
  scopes ARRAY NOT NULL DEFAULT '{}'::text[],
  expires_at timestamp with time zone,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'expired'::text, 'revoked'::text, 'invalid'::text, 'inactive'::text])),
  last_verified_at timestamp with time zone,
  last_used_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT meta_credentials_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT meta_credentials_meta_app_id_fkey FOREIGN KEY (meta_app_id) REFERENCES public.meta_apps(id),
  CONSTRAINT meta_credentials_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT meta_credentials_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id),
  CONSTRAINT meta_credentials_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.user_business_access (
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  business_portfolio_id uuid NOT NULL,
  can_read boolean NOT NULL DEFAULT true,
  can_manage boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  can_send boolean NOT NULL DEFAULT false,
  CONSTRAINT user_business_access_pkey PRIMARY KEY (user_id, business_portfolio_id),
  CONSTRAINT user_business_access_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT user_business_access_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_business_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_waba_access (
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  waba_id uuid NOT NULL,
  can_read boolean NOT NULL DEFAULT true,
  can_manage boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  can_send boolean NOT NULL DEFAULT false,
  CONSTRAINT user_waba_access_pkey PRIMARY KEY (user_id, waba_id),
  CONSTRAINT user_waba_access_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_waba_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_waba_access_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id)
);
CREATE TABLE public.user_number_access (
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  whatsapp_number_id uuid NOT NULL,
  can_read boolean NOT NULL DEFAULT true,
  can_send boolean NOT NULL DEFAULT false,
  can_manage boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_number_access_pkey PRIMARY KEY (user_id, whatsapp_number_id),
  CONSTRAINT user_number_access_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT user_number_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_number_access_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.team_number_access (
  organization_id uuid NOT NULL,
  team_id uuid NOT NULL,
  whatsapp_number_id uuid NOT NULL,
  can_read boolean NOT NULL DEFAULT true,
  can_send boolean NOT NULL DEFAULT false,
  can_manage boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_number_access_pkey PRIMARY KEY (team_id, whatsapp_number_id),
  CONSTRAINT team_number_access_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT team_number_access_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_number_access_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  display_name text,
  first_name text,
  last_name text,
  email text,
  company text,
  source text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'blocked'::text, 'archived'::text])),
  assigned_user_id uuid,
  assigned_team_id uuid,
  notes text,
  custom_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
  first_interaction_at timestamp with time zone,
  last_interaction_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contacts_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES auth.users(id),
  CONSTRAINT contacts_assigned_team_id_fkey FOREIGN KEY (assigned_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.contact_channels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  channel_type text NOT NULL DEFAULT 'whatsapp'::text CHECK (channel_type = ANY (ARRAY['whatsapp'::text, 'phone'::text, 'email'::text, 'other'::text])),
  address text NOT NULL,
  normalized_address text,
  wa_id text,
  profile_name text,
  is_primary boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contact_channels_pkey PRIMARY KEY (id),
  CONSTRAINT contact_channels_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contact_channels_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  color_key text,
  category text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tags_pkey PRIMARY KEY (id),
  CONSTRAINT tags_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.contact_tags (
  contact_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contact_tags_pkey PRIMARY KEY (contact_id, tag_id),
  CONSTRAINT contact_tags_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT contact_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id)
);
CREATE TABLE public.contact_consents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  whatsapp_number_id uuid,
  consent_type text NOT NULL CHECK (consent_type = ANY (ARRAY['marketing'::text, 'service'::text, 'transactional'::text, 'other'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['opt_in'::text, 'opt_out'::text, 'unknown'::text])),
  source text,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  effective_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT contact_consents_pkey PRIMARY KEY (id),
  CONSTRAINT contact_consents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT contact_consents_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT contact_consents_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  whatsapp_number_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  contact_channel_id uuid,
  meta_conversation_id text,
  category text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'pending'::text, 'waiting_customer'::text, 'resolved'::text, 'closed'::text, 'spam'::text])),
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  assigned_user_id uuid,
  assigned_team_id uuid,
  last_message_at timestamp with time zone,
  last_incoming_at timestamp with time zone,
  last_outgoing_at timestamp with time zone,
  unread_count integer NOT NULL DEFAULT 0 CHECK (unread_count >= 0),
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  closed_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT conversations_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT conversations_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT conversations_contact_channel_id_fkey FOREIGN KEY (contact_channel_id) REFERENCES public.contact_channels(id),
  CONSTRAINT conversations_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_assigned_team_id_fkey FOREIGN KEY (assigned_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.conversation_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  assigned_user_id uuid,
  assigned_team_id uuid,
  assigned_by uuid,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  reason text,
  CONSTRAINT conversation_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_assignments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT conversation_assignments_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT conversation_assignments_assigned_user_id_fkey FOREIGN KEY (assigned_user_id) REFERENCES auth.users(id),
  CONSTRAINT conversation_assignments_assigned_team_id_fkey FOREIGN KEY (assigned_team_id) REFERENCES public.teams(id),
  CONSTRAINT conversation_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.conversation_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  author_user_id uuid NOT NULL,
  body text NOT NULL,
  is_pinned boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT conversation_notes_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_notes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT conversation_notes_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT conversation_notes_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  conversation_id uuid,
  whatsapp_number_id uuid NOT NULL,
  contact_id uuid,
  contact_channel_id uuid,
  meta_message_id text,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['incoming'::text, 'outgoing'::text, 'system'::text])),
  message_type text NOT NULL,
  body text,
  caption text,
  reply_to_message_id uuid,
  meta_reply_to_message_id text,
  status text NOT NULL DEFAULT 'received'::text CHECK (status = ANY (ARRAY['received'::text, 'queued'::text, 'submitted'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text, 'deleted'::text, 'unknown'::text])),
  interactive_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  context_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  meta_timestamp timestamp with time zone,
  received_at timestamp with time zone,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT messages_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT messages_contact_channel_id_fkey FOREIGN KEY (contact_channel_id) REFERENCES public.contact_channels(id),
  CONSTRAINT messages_reply_to_message_id_fkey FOREIGN KEY (reply_to_message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.message_status_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  message_id uuid NOT NULL,
  whatsapp_number_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['received'::text, 'queued'::text, 'submitted'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text, 'deleted'::text, 'unknown'::text])),
  meta_timestamp timestamp with time zone,
  error_code text,
  error_message text,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT message_status_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT message_status_history_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT message_status_history_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  whatsapp_number_id uuid NOT NULL,
  message_id uuid NOT NULL,
  contact_id uuid,
  meta_media_id text,
  media_type text NOT NULL,
  mime_type text,
  filename text,
  file_size bigint CHECK (file_size IS NULL OR file_size >= 0),
  sha256 text,
  storage_provider text NOT NULL DEFAULT 'supabase'::text,
  storage_bucket text NOT NULL DEFAULT 'azwa-whatsapp-media'::text,
  storage_path text,
  download_status text NOT NULL DEFAULT 'pending'::text CHECK (download_status = ANY (ARRAY['pending'::text, 'downloading'::text, 'stored'::text, 'failed'::text, 'expired'::text, 'deleted'::text])),
  download_attempts integer NOT NULL DEFAULT 0 CHECK (download_attempts >= 0),
  last_error text,
  received_at timestamp with time zone,
  stored_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT media_pkey PRIMARY KEY (id),
  CONSTRAINT media_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT media_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT media_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT media_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id)
);
CREATE TABLE public.templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  waba_id uuid NOT NULL,
  meta_template_id text,
  name text NOT NULL,
  category text,
  language text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'approved'::text, 'rejected'::text, 'paused'::text, 'disabled'::text, 'deleted'::text, 'unknown'::text])),
  quality_rating text,
  components jsonb NOT NULL DEFAULT '[]'::jsonb,
  rejection_reason text,
  last_synced_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT templates_pkey PRIMARY KEY (id),
  CONSTRAINT templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT templates_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id)
);
CREATE TABLE public.template_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  template_id uuid NOT NULL,
  version_no integer NOT NULL CHECK (version_no > 0),
  snapshot jsonb NOT NULL,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT template_versions_pkey PRIMARY KEY (id),
  CONSTRAINT template_versions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT template_versions_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id),
  CONSTRAINT template_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  sender_whatsapp_number_id uuid NOT NULL,
  template_id uuid,
  name text NOT NULL,
  description text,
  audience_filter jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'running'::text, 'paused'::text, 'completed'::text, 'cancelled'::text, 'failed'::text])),
  scheduled_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  stats jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT campaigns_sender_whatsapp_number_id_fkey FOREIGN KEY (sender_whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT campaigns_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.templates(id),
  CONSTRAINT campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.campaign_recipients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  campaign_id uuid NOT NULL,
  contact_id uuid,
  contact_channel_id uuid,
  recipient_address text NOT NULL,
  template_variables jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'processing'::text, 'submitted'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text, 'skipped'::text, 'cancelled'::text])),
  message_id uuid,
  error_code text,
  error_message text,
  queued_at timestamp with time zone NOT NULL DEFAULT now(),
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  failed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campaign_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_recipients_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_recipients_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT campaign_recipients_contact_channel_id_fkey FOREIGN KEY (contact_channel_id) REFERENCES public.contact_channels(id),
  CONSTRAINT campaign_recipients_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id)
);
CREATE TABLE public.automation_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  trigger_type text NOT NULL,
  trigger_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  conditions jsonb NOT NULL DEFAULT '[]'::jsonb,
  actions jsonb NOT NULL DEFAULT '[]'::jsonb,
  scope_business_portfolio_id uuid,
  scope_waba_id uuid,
  scope_whatsapp_number_id uuid,
  is_enabled boolean NOT NULL DEFAULT true,
  priority integer NOT NULL DEFAULT 100,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT automation_rules_pkey PRIMARY KEY (id),
  CONSTRAINT automation_rules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT automation_rules_scope_business_portfolio_id_fkey FOREIGN KEY (scope_business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT automation_rules_scope_waba_id_fkey FOREIGN KEY (scope_waba_id) REFERENCES public.wabas(id),
  CONSTRAINT automation_rules_scope_whatsapp_number_id_fkey FOREIGN KEY (scope_whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT automation_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.automation_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  automation_rule_id uuid NOT NULL,
  trigger_event_id uuid,
  conversation_id uuid,
  message_id uuid,
  whatsapp_number_id uuid,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'failed'::text, 'skipped'::text, 'cancelled'::text])),
  input_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  output_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT automation_runs_pkey PRIMARY KEY (id),
  CONSTRAINT automation_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT automation_runs_automation_rule_id_fkey FOREIGN KEY (automation_rule_id) REFERENCES public.automation_rules(id),
  CONSTRAINT automation_runs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT automation_runs_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT automation_runs_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.webhook_endpoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  meta_app_id uuid,
  endpoint_type text NOT NULL DEFAULT 'meta_whatsapp'::text,
  url text NOT NULL,
  verify_token_credential_id uuid,
  app_secret_credential_id uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'error'::text])),
  verification_status text,
  last_event_at timestamp with time zone,
  last_success_at timestamp with time zone,
  last_failure_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_endpoints_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_endpoints_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT webhook_endpoints_meta_app_id_fkey FOREIGN KEY (meta_app_id) REFERENCES public.meta_apps(id),
  CONSTRAINT webhook_endpoints_verify_token_credential_id_fkey FOREIGN KEY (verify_token_credential_id) REFERENCES public.meta_credentials(id),
  CONSTRAINT webhook_endpoints_app_secret_credential_id_fkey FOREIGN KEY (app_secret_credential_id) REFERENCES public.meta_credentials(id)
);
CREATE TABLE public.webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  webhook_endpoint_id uuid,
  meta_app_id uuid,
  business_portfolio_id uuid,
  waba_id uuid,
  whatsapp_number_id uuid,
  meta_waba_id text,
  meta_phone_number_id text,
  event_type text NOT NULL,
  meta_message_id text,
  deduplication_key text NOT NULL,
  signature_valid boolean,
  payload jsonb NOT NULL,
  status text NOT NULL DEFAULT 'received'::text CHECK (status = ANY (ARRAY['received'::text, 'queued'::text, 'processing'::text, 'processed'::text, 'failed'::text, 'ignored'::text, 'unmapped_number_event'::text])),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  error text,
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  queued_at timestamp with time zone,
  processed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_events_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT webhook_events_webhook_endpoint_id_fkey FOREIGN KEY (webhook_endpoint_id) REFERENCES public.webhook_endpoints(id),
  CONSTRAINT webhook_events_meta_app_id_fkey FOREIGN KEY (meta_app_id) REFERENCES public.meta_apps(id),
  CONSTRAINT webhook_events_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT webhook_events_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id),
  CONSTRAINT webhook_events_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.api_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  correlation_id text,
  request_id text,
  meta_app_id uuid,
  business_portfolio_id uuid,
  waba_id uuid,
  whatsapp_number_id uuid,
  endpoint text NOT NULL,
  method text NOT NULL,
  http_status integer,
  duration_ms integer,
  meta_error_code text,
  meta_error_message text,
  request_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT api_requests_pkey PRIMARY KEY (id),
  CONSTRAINT api_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT api_requests_meta_app_id_fkey FOREIGN KEY (meta_app_id) REFERENCES public.meta_apps(id),
  CONSTRAINT api_requests_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT api_requests_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id),
  CONSTRAINT api_requests_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.api_errors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  api_request_id uuid,
  whatsapp_number_id uuid,
  waba_id uuid,
  error_type text,
  error_code text,
  title text,
  message text,
  raw_error jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'acknowledged'::text, 'resolved'::text, 'ignored'::text])),
  occurrence_count integer NOT NULL DEFAULT 1 CHECK (occurrence_count > 0),
  first_occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  last_occurred_at timestamp with time zone NOT NULL DEFAULT now(),
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT api_errors_pkey PRIMARY KEY (id),
  CONSTRAINT api_errors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT api_errors_api_request_id_fkey FOREIGN KEY (api_request_id) REFERENCES public.api_requests(id),
  CONSTRAINT api_errors_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT api_errors_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id)
);
CREATE TABLE public.health_checks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  business_portfolio_id uuid,
  waba_id uuid,
  whatsapp_number_id uuid,
  component text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['healthy'::text, 'warning'::text, 'critical'::text, 'offline'::text, 'unknown'::text])),
  score numeric,
  message text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  checked_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT health_checks_pkey PRIMARY KEY (id),
  CONSTRAINT health_checks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT health_checks_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT health_checks_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id),
  CONSTRAINT health_checks_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  business_portfolio_id uuid,
  waba_id uuid,
  whatsapp_number_id uuid,
  alert_type text NOT NULL,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])),
  title text NOT NULL,
  message text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'acknowledged'::text, 'resolved'::text, 'ignored'::text])),
  source_entity_type text,
  source_entity_id uuid,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  acknowledged_at timestamp with time zone,
  resolved_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT alerts_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT alerts_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id),
  CONSTRAINT alerts_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  queue_name text NOT NULL,
  job_type text NOT NULL,
  deduplication_key text,
  priority integer NOT NULL DEFAULT 100,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  max_attempts integer NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
  available_at timestamp with time zone NOT NULL DEFAULT now(),
  locked_at timestamp with time zone,
  locked_by text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  failed_at timestamp with time zone,
  error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.dead_letter_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  original_job_id uuid,
  queue_name text NOT NULL,
  job_type text NOT NULL,
  payload jsonb NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  last_error text,
  failed_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'retried'::text, 'discarded'::text, 'resolved'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT dead_letter_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT dead_letter_jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT dead_letter_jobs_original_job_id_fkey FOREIGN KEY (original_job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  integration_type text NOT NULL,
  name text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'error'::text])),
  config jsonb NOT NULL DEFAULT '{}'::jsonb,
  secret_reference text,
  last_success_at timestamp with time zone,
  last_failure_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT integrations_pkey PRIMARY KEY (id),
  CONSTRAINT integrations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.outgoing_webhooks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  target_url text NOT NULL,
  event_types ARRAY NOT NULL,
  secret_reference text,
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT outgoing_webhooks_pkey PRIMARY KEY (id),
  CONSTRAINT outgoing_webhooks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.outgoing_webhook_deliveries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  outgoing_webhook_id uuid NOT NULL,
  event_type text NOT NULL,
  event_id uuid,
  payload jsonb NOT NULL,
  attempt integer NOT NULL DEFAULT 0,
  http_status integer,
  response_excerpt text,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'sending'::text, 'delivered'::text, 'failed'::text])),
  next_retry_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  delivered_at timestamp with time zone,
  CONSTRAINT outgoing_webhook_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT outgoing_webhook_deliveries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT outgoing_webhook_deliveries_outgoing_webhook_id_fkey FOREIGN KEY (outgoing_webhook_id) REFERENCES public.outgoing_webhooks(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  key text NOT NULL,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_secret boolean NOT NULL DEFAULT false,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  actor_user_id uuid,
  business_portfolio_id uuid,
  waba_id uuid,
  whatsapp_number_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  old_value jsonb,
  new_value jsonb,
  ip inet,
  user_agent text,
  correlation_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id),
  CONSTRAINT audit_logs_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT audit_logs_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id),
  CONSTRAINT audit_logs_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id)
);
CREATE TABLE public.meta_sync_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  business_portfolio_id uuid,
  waba_id uuid,
  whatsapp_number_id uuid,
  sync_type text NOT NULL CHECK (sync_type = ANY (ARRAY['business'::text, 'wabas'::text, 'numbers'::text, 'templates'::text, 'number_health'::text, 'full'::text])),
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'completed'::text, 'partial'::text, 'failed'::text, 'cancelled'::text])),
  requested_by uuid,
  stats jsonb NOT NULL DEFAULT '{}'::jsonb,
  error text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT meta_sync_runs_pkey PRIMARY KEY (id),
  CONSTRAINT meta_sync_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT meta_sync_runs_business_portfolio_id_fkey FOREIGN KEY (business_portfolio_id) REFERENCES public.business_portfolios(id),
  CONSTRAINT meta_sync_runs_waba_id_fkey FOREIGN KEY (waba_id) REFERENCES public.wabas(id),
  CONSTRAINT meta_sync_runs_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT meta_sync_runs_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id)
);
CREATE TABLE public.message_outbox (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  whatsapp_number_id uuid NOT NULL,
  contact_id uuid,
  conversation_id uuid,
  campaign_id uuid,
  campaign_recipient_id uuid,
  recipient_address text NOT NULL,
  message_type text NOT NULL,
  request_payload jsonb NOT NULL,
  idempotency_key text NOT NULL,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'sending'::text, 'submitted'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text, 'cancelled'::text])),
  meta_message_id text,
  requested_by uuid,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at timestamp with time zone NOT NULL DEFAULT now(),
  last_error text,
  submitted_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_outbox_pkey PRIMARY KEY (id),
  CONSTRAINT message_outbox_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT message_outbox_whatsapp_number_id_fkey FOREIGN KEY (whatsapp_number_id) REFERENCES public.whatsapp_numbers(id),
  CONSTRAINT message_outbox_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.contacts(id),
  CONSTRAINT message_outbox_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT message_outbox_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT message_outbox_campaign_recipient_id_fkey FOREIGN KEY (campaign_recipient_id) REFERENCES public.campaign_recipients(id),
  CONSTRAINT message_outbox_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id)
);
CREATE TABLE public.message_send_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  outbox_id uuid NOT NULL,
  api_request_id uuid,
  attempt_no integer NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['started'::text, 'submitted'::text, 'failed'::text])),
  http_status integer,
  error_code text,
  error_message text,
  response_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT message_send_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT message_send_attempts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT message_send_attempts_outbox_id_fkey FOREIGN KEY (outbox_id) REFERENCES public.message_outbox(id),
  CONSTRAINT message_send_attempts_api_request_id_fkey FOREIGN KEY (api_request_id) REFERENCES public.api_requests(id)
);
CREATE TABLE public.webhook_event_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  webhook_event_id uuid NOT NULL,
  attempt_no integer NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['started'::text, 'processed'::text, 'failed'::text, 'ignored'::text])),
  error text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT webhook_event_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_event_attempts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT webhook_event_attempts_webhook_event_id_fkey FOREIGN KEY (webhook_event_id) REFERENCES public.webhook_events(id)
);
CREATE TABLE public.media_download_attempts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  media_id uuid NOT NULL,
  attempt_no integer NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['started'::text, 'stored'::text, 'failed'::text])),
  http_status integer,
  error text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT media_download_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT media_download_attempts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT media_download_attempts_media_id_fkey FOREIGN KEY (media_id) REFERENCES public.media(id)
);
