/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedApiLogsRouteImport } from './routes/_authenticated/api-logs'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCredentialsRouteImport } from './routes/_authenticated/credentials'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDeadLetterRouteImport } from './routes/_authenticated/dead-letter'
import { Route as AuthenticatedErrorsRouteImport } from './routes/_authenticated/errors'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedInfrastructureRouteImport } from './routes/_authenticated/infrastructure'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedMetaAppRouteImport } from './routes/_authenticated/meta-app'
import { Route as AuthenticatedNumbersRouteImport } from './routes/_authenticated/numbers'
import { Route as AuthenticatedQueuesRouteImport } from './routes/_authenticated/queues'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWabasRouteImport } from './routes/_authenticated/wabas'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as LegacyIndexRouteImport } from './routes/legacy.index'
import { Route as LegacyAccountsRouteImport } from './routes/legacy.accounts'
import { Route as LegacyClientsRouteImport } from './routes/legacy.clients'
import { Route as LegacyFinanceRouteImport } from './routes/legacy.finance'
import { Route as LegacyFlowsRouteImport } from './routes/legacy.flows'
import { Route as LegacyInboxRouteImport } from './routes/legacy.inbox'
import { Route as LegacyLoginRouteImport } from './routes/legacy.login'
import { Route as LegacyMaintenanceRouteImport } from './routes/legacy.maintenance'
import { Route as LegacyProjectsRouteImport } from './routes/legacy.projects'
import { Route as LegacySettingsRouteImport } from './routes/legacy.settings'
import { Route as LegacyTeamsRouteImport } from './routes/legacy.teams'
import { Route as LegacyTemplatesRouteImport } from './routes/legacy.templates'
import { Route as LegacyWebhooksRouteImport } from './routes/legacy.webhooks'
import { Route as LegacyFlowsIndexRouteImport } from './routes/legacy.flows.index'
import { Route as LegacyFlowsNewRouteImport } from './routes/legacy.flows.new'
import { Route as ApiPublicJobsMediaRouteImport } from './routes/api/public/jobs/media'
import { Route as ApiPublicWebhooksMetaWhatsappRouteImport } from './routes/api/public/webhooks/meta/whatsapp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiLogsRoute = AuthenticatedApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCredentialsRoute =
  AuthenticatedCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeadLetterRoute = AuthenticatedDeadLetterRouteImport.update({
  id: '/dead-letter',
  path: '/dead-letter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsRoute = AuthenticatedErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInfrastructureRoute =
  AuthenticatedInfrastructureRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetaAppRoute = AuthenticatedMetaAppRouteImport.update({
  id: '/meta-app',
  path: '/meta-app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNumbersRoute = AuthenticatedNumbersRouteImport.update({
  id: '/numbers',
  path: '/numbers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueuesRoute = AuthenticatedQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWabasRoute = AuthenticatedWabasRouteImport.update({
  id: '/wabas',
  path: '/wabas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyAccountsRoute = LegacyAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyClientsRoute = LegacyClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyFinanceRoute = LegacyFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyFlowsRoute = LegacyFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyInboxRoute = LegacyInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyLoginRoute = LegacyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyMaintenanceRoute = LegacyMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyProjectsRoute = LegacyProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacySettingsRoute = LegacySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyTeamsRoute = LegacyTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyTemplatesRoute = LegacyTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyWebhooksRoute = LegacyWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => LegacyRoute,
} as any)
const LegacyFlowsIndexRoute = LegacyFlowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyFlowsRoute,
} as any)
const LegacyFlowsNewRoute = LegacyFlowsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LegacyFlowsRoute,
} as any)
const ApiPublicJobsMediaRoute = ApiPublicJobsMediaRouteImport.update({
  id: '/api/public/jobs/media',
  path: '/api/public/jobs/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMetaWhatsappRoute =
  ApiPublicWebhooksMetaWhatsappRouteImport.update({
    id: '/api/public/webhooks/meta/whatsapp',
    path: '/api/public/webhooks/meta/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/healthz': typeof HealthzRoute
  '/legacy': typeof LegacyRouteWithChildren
  '/readyz': typeof ReadyzRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/api-logs': typeof AuthenticatedApiLogsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/credentials': typeof AuthenticatedCredentialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dead-letter': typeof AuthenticatedDeadLetterRoute
  '/errors': typeof AuthenticatedErrorsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/infrastructure': typeof AuthenticatedInfrastructureRoute
  '/media': typeof AuthenticatedMediaRoute
  '/meta-app': typeof AuthenticatedMetaAppRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wabas': typeof AuthenticatedWabasRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/legacy/accounts': typeof LegacyAccountsRoute
  '/legacy/clients': typeof LegacyClientsRoute
  '/legacy/finance': typeof LegacyFinanceRoute
  '/legacy/flows': typeof LegacyFlowsRouteWithChildren
  '/legacy/inbox': typeof LegacyInboxRoute
  '/legacy/login': typeof LegacyLoginRoute
  '/legacy/maintenance': typeof LegacyMaintenanceRoute
  '/legacy/projects': typeof LegacyProjectsRoute
  '/legacy/settings': typeof LegacySettingsRoute
  '/legacy/teams': typeof LegacyTeamsRoute
  '/legacy/templates': typeof LegacyTemplatesRoute
  '/legacy/webhooks': typeof LegacyWebhooksRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/flows/new': typeof LegacyFlowsNewRoute
  '/legacy/flows/': typeof LegacyFlowsIndexRoute
  '/api/public/jobs/media': typeof ApiPublicJobsMediaRoute
  '/api/public/webhooks/meta/whatsapp': typeof ApiPublicWebhooksMetaWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/healthz': typeof HealthzRoute
  '/readyz': typeof ReadyzRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/api-logs': typeof AuthenticatedApiLogsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/credentials': typeof AuthenticatedCredentialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dead-letter': typeof AuthenticatedDeadLetterRoute
  '/errors': typeof AuthenticatedErrorsRoute
  '/health': typeof AuthenticatedHealthRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/infrastructure': typeof AuthenticatedInfrastructureRoute
  '/media': typeof AuthenticatedMediaRoute
  '/meta-app': typeof AuthenticatedMetaAppRoute
  '/numbers': typeof AuthenticatedNumbersRoute
  '/queues': typeof AuthenticatedQueuesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wabas': typeof AuthenticatedWabasRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/legacy/accounts': typeof LegacyAccountsRoute
  '/legacy/clients': typeof LegacyClientsRoute
  '/legacy/finance': typeof LegacyFinanceRoute
  '/legacy/inbox': typeof LegacyInboxRoute
  '/legacy/login': typeof LegacyLoginRoute
  '/legacy/maintenance': typeof LegacyMaintenanceRoute
  '/legacy/projects': typeof LegacyProjectsRoute
  '/legacy/settings': typeof LegacySettingsRoute
  '/legacy/teams': typeof LegacyTeamsRoute
  '/legacy/templates': typeof LegacyTemplatesRoute
  '/legacy/webhooks': typeof LegacyWebhooksRoute
  '/legacy': typeof LegacyIndexRoute
  '/legacy/flows/new': typeof LegacyFlowsNewRoute
  '/legacy/flows': typeof LegacyFlowsIndexRoute
  '/api/public/jobs/media': typeof ApiPublicJobsMediaRoute
  '/api/public/webhooks/meta/whatsapp': typeof ApiPublicWebhooksMetaWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/healthz': typeof HealthzRoute
  '/legacy': typeof LegacyRouteWithChildren
  '/readyz': typeof ReadyzRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/api-logs': typeof AuthenticatedApiLogsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/credentials': typeof AuthenticatedCredentialsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dead-letter': typeof AuthenticatedDeadLetterRoute
  '/_authenticated/errors': typeof AuthenticatedErrorsRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/infrastructure': typeof AuthenticatedInfrastructureRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/meta-app': typeof AuthenticatedMetaAppRoute
  '/_authenticated/numbers': typeof AuthenticatedNumbersRoute
  '/_authenticated/queues': typeof AuthenticatedQueuesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/wabas': typeof AuthenticatedWabasRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/legacy/accounts': typeof LegacyAccountsRoute
  '/legacy/clients': typeof LegacyClientsRoute
  '/legacy/finance': typeof LegacyFinanceRoute
  '/legacy/flows': typeof LegacyFlowsRouteWithChildren
  '/legacy/inbox': typeof LegacyInboxRoute
  '/legacy/login': typeof LegacyLoginRoute
  '/legacy/maintenance': typeof LegacyMaintenanceRoute
  '/legacy/projects': typeof LegacyProjectsRoute
  '/legacy/settings': typeof LegacySettingsRoute
  '/legacy/teams': typeof LegacyTeamsRoute
  '/legacy/templates': typeof LegacyTemplatesRoute
  '/legacy/webhooks': typeof LegacyWebhooksRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/flows/new': typeof LegacyFlowsNewRoute
  '/legacy/flows/': typeof LegacyFlowsIndexRoute
  '/api/public/jobs/media': typeof ApiPublicJobsMediaRoute
  '/api/public/webhooks/meta/whatsapp': typeof ApiPublicWebhooksMetaWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/healthz'
    | '/legacy'
    | '/readyz'
    | '/alerts'
    | '/analytics'
    | '/api-logs'
    | '/audit'
    | '/automation'
    | '/campaigns'
    | '/contacts'
    | '/credentials'
    | '/dashboard'
    | '/dead-letter'
    | '/errors'
    | '/health'
    | '/inbox'
    | '/infrastructure'
    | '/media'
    | '/meta-app'
    | '/numbers'
    | '/queues'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/users'
    | '/wabas'
    | '/webhooks'
    | '/legacy/accounts'
    | '/legacy/clients'
    | '/legacy/finance'
    | '/legacy/flows'
    | '/legacy/inbox'
    | '/legacy/login'
    | '/legacy/maintenance'
    | '/legacy/projects'
    | '/legacy/settings'
    | '/legacy/teams'
    | '/legacy/templates'
    | '/legacy/webhooks'
    | '/legacy/'
    | '/legacy/flows/new'
    | '/legacy/flows/'
    | '/api/public/jobs/media'
    | '/api/public/webhooks/meta/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/healthz'
    | '/readyz'
    | '/alerts'
    | '/analytics'
    | '/api-logs'
    | '/audit'
    | '/automation'
    | '/campaigns'
    | '/contacts'
    | '/credentials'
    | '/dashboard'
    | '/dead-letter'
    | '/errors'
    | '/health'
    | '/inbox'
    | '/infrastructure'
    | '/media'
    | '/meta-app'
    | '/numbers'
    | '/queues'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/users'
    | '/wabas'
    | '/webhooks'
    | '/legacy/accounts'
    | '/legacy/clients'
    | '/legacy/finance'
    | '/legacy/inbox'
    | '/legacy/login'
    | '/legacy/maintenance'
    | '/legacy/projects'
    | '/legacy/settings'
    | '/legacy/teams'
    | '/legacy/templates'
    | '/legacy/webhooks'
    | '/legacy'
    | '/legacy/flows/new'
    | '/legacy/flows'
    | '/api/public/jobs/media'
    | '/api/public/webhooks/meta/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/healthz'
    | '/legacy'
    | '/readyz'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/api-logs'
    | '/_authenticated/audit'
    | '/_authenticated/automation'
    | '/_authenticated/campaigns'
    | '/_authenticated/contacts'
    | '/_authenticated/credentials'
    | '/_authenticated/dashboard'
    | '/_authenticated/dead-letter'
    | '/_authenticated/errors'
    | '/_authenticated/health'
    | '/_authenticated/inbox'
    | '/_authenticated/infrastructure'
    | '/_authenticated/media'
    | '/_authenticated/meta-app'
    | '/_authenticated/numbers'
    | '/_authenticated/queues'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/users'
    | '/_authenticated/wabas'
    | '/_authenticated/webhooks'
    | '/legacy/accounts'
    | '/legacy/clients'
    | '/legacy/finance'
    | '/legacy/flows'
    | '/legacy/inbox'
    | '/legacy/login'
    | '/legacy/maintenance'
    | '/legacy/projects'
    | '/legacy/settings'
    | '/legacy/teams'
    | '/legacy/templates'
    | '/legacy/webhooks'
    | '/legacy/'
    | '/legacy/flows/new'
    | '/legacy/flows/'
    | '/api/public/jobs/media'
    | '/api/public/webhooks/meta/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  HealthzRoute: typeof HealthzRoute
  LegacyRoute: typeof LegacyRouteWithChildren
  ReadyzRoute: typeof ReadyzRoute
  ApiPublicJobsMediaRoute: typeof ApiPublicJobsMediaRoute
  ApiPublicWebhooksMetaWhatsappRoute: typeof ApiPublicWebhooksMetaWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-logs': {
      id: '/_authenticated/api-logs'
      path: '/api-logs'
      fullPath: '/api-logs'
      preLoaderRoute: typeof AuthenticatedApiLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credentials': {
      id: '/_authenticated/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AuthenticatedCredentialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dead-letter': {
      id: '/_authenticated/dead-letter'
      path: '/dead-letter'
      fullPath: '/dead-letter'
      preLoaderRoute: typeof AuthenticatedDeadLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors': {
      id: '/_authenticated/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof AuthenticatedErrorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure': {
      id: '/_authenticated/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof AuthenticatedInfrastructureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meta-app': {
      id: '/_authenticated/meta-app'
      path: '/meta-app'
      fullPath: '/meta-app'
      preLoaderRoute: typeof AuthenticatedMetaAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/numbers': {
      id: '/_authenticated/numbers'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof AuthenticatedNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queues': {
      id: '/_authenticated/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof AuthenticatedQueuesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wabas': {
      id: '/_authenticated/wabas'
      path: '/wabas'
      fullPath: '/wabas'
      preLoaderRoute: typeof AuthenticatedWabasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legacy/': {
      id: '/legacy/'
      path: '/'
      fullPath: '/legacy/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/accounts': {
      id: '/legacy/accounts'
      path: '/accounts'
      fullPath: '/legacy/accounts'
      preLoaderRoute: typeof LegacyAccountsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/clients': {
      id: '/legacy/clients'
      path: '/clients'
      fullPath: '/legacy/clients'
      preLoaderRoute: typeof LegacyClientsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/finance': {
      id: '/legacy/finance'
      path: '/finance'
      fullPath: '/legacy/finance'
      preLoaderRoute: typeof LegacyFinanceRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/flows': {
      id: '/legacy/flows'
      path: '/flows'
      fullPath: '/legacy/flows'
      preLoaderRoute: typeof LegacyFlowsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/inbox': {
      id: '/legacy/inbox'
      path: '/inbox'
      fullPath: '/legacy/inbox'
      preLoaderRoute: typeof LegacyInboxRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/login': {
      id: '/legacy/login'
      path: '/login'
      fullPath: '/legacy/login'
      preLoaderRoute: typeof LegacyLoginRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/maintenance': {
      id: '/legacy/maintenance'
      path: '/maintenance'
      fullPath: '/legacy/maintenance'
      preLoaderRoute: typeof LegacyMaintenanceRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/projects': {
      id: '/legacy/projects'
      path: '/projects'
      fullPath: '/legacy/projects'
      preLoaderRoute: typeof LegacyProjectsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/settings': {
      id: '/legacy/settings'
      path: '/settings'
      fullPath: '/legacy/settings'
      preLoaderRoute: typeof LegacySettingsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/teams': {
      id: '/legacy/teams'
      path: '/teams'
      fullPath: '/legacy/teams'
      preLoaderRoute: typeof LegacyTeamsRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/templates': {
      id: '/legacy/templates'
      path: '/templates'
      fullPath: '/legacy/templates'
      preLoaderRoute: typeof LegacyTemplatesRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/webhooks': {
      id: '/legacy/webhooks'
      path: '/webhooks'
      fullPath: '/legacy/webhooks'
      preLoaderRoute: typeof LegacyWebhooksRouteImport
      parentRoute: typeof LegacyRoute
    }
    '/legacy/flows/': {
      id: '/legacy/flows/'
      path: '/'
      fullPath: '/legacy/flows/'
      preLoaderRoute: typeof LegacyFlowsIndexRouteImport
      parentRoute: typeof LegacyFlowsRoute
    }
    '/legacy/flows/new': {
      id: '/legacy/flows/new'
      path: '/new'
      fullPath: '/legacy/flows/new'
      preLoaderRoute: typeof LegacyFlowsNewRouteImport
      parentRoute: typeof LegacyFlowsRoute
    }
    '/api/public/jobs/media': {
      id: '/api/public/jobs/media'
      path: '/api/public/jobs/media'
      fullPath: '/api/public/jobs/media'
      preLoaderRoute: typeof ApiPublicJobsMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta/whatsapp': {
      id: '/api/public/webhooks/meta/whatsapp'
      path: '/api/public/webhooks/meta/whatsapp'
      fullPath: '/api/public/webhooks/meta/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksMetaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedApiLogsRoute: typeof AuthenticatedApiLogsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedCredentialsRoute: typeof AuthenticatedCredentialsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeadLetterRoute: typeof AuthenticatedDeadLetterRoute
  AuthenticatedErrorsRoute: typeof AuthenticatedErrorsRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedInfrastructureRoute: typeof AuthenticatedInfrastructureRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedMetaAppRoute: typeof AuthenticatedMetaAppRoute
  AuthenticatedNumbersRoute: typeof AuthenticatedNumbersRoute
  AuthenticatedQueuesRoute: typeof AuthenticatedQueuesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWabasRoute: typeof AuthenticatedWabasRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedApiLogsRoute: AuthenticatedApiLogsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedCredentialsRoute: AuthenticatedCredentialsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeadLetterRoute: AuthenticatedDeadLetterRoute,
  AuthenticatedErrorsRoute: AuthenticatedErrorsRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedInfrastructureRoute: AuthenticatedInfrastructureRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedMetaAppRoute: AuthenticatedMetaAppRoute,
  AuthenticatedNumbersRoute: AuthenticatedNumbersRoute,
  AuthenticatedQueuesRoute: AuthenticatedQueuesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWabasRoute: AuthenticatedWabasRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LegacyFlowsRouteChildren {
  LegacyFlowsNewRoute: typeof LegacyFlowsNewRoute
  LegacyFlowsIndexRoute: typeof LegacyFlowsIndexRoute
}

const LegacyFlowsRouteChildren: LegacyFlowsRouteChildren = {
  LegacyFlowsNewRoute: LegacyFlowsNewRoute,
  LegacyFlowsIndexRoute: LegacyFlowsIndexRoute,
}

const LegacyFlowsRouteWithChildren = LegacyFlowsRoute._addFileChildren(
  LegacyFlowsRouteChildren,
)

interface LegacyRouteChildren {
  LegacyAccountsRoute: typeof LegacyAccountsRoute
  LegacyClientsRoute: typeof LegacyClientsRoute
  LegacyFinanceRoute: typeof LegacyFinanceRoute
  LegacyFlowsRoute: typeof LegacyFlowsRouteWithChildren
  LegacyInboxRoute: typeof LegacyInboxRoute
  LegacyLoginRoute: typeof LegacyLoginRoute
  LegacyMaintenanceRoute: typeof LegacyMaintenanceRoute
  LegacyProjectsRoute: typeof LegacyProjectsRoute
  LegacySettingsRoute: typeof LegacySettingsRoute
  LegacyTeamsRoute: typeof LegacyTeamsRoute
  LegacyTemplatesRoute: typeof LegacyTemplatesRoute
  LegacyWebhooksRoute: typeof LegacyWebhooksRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
}

const LegacyRouteChildren: LegacyRouteChildren = {
  LegacyAccountsRoute: LegacyAccountsRoute,
  LegacyClientsRoute: LegacyClientsRoute,
  LegacyFinanceRoute: LegacyFinanceRoute,
  LegacyFlowsRoute: LegacyFlowsRouteWithChildren,
  LegacyInboxRoute: LegacyInboxRoute,
  LegacyLoginRoute: LegacyLoginRoute,
  LegacyMaintenanceRoute: LegacyMaintenanceRoute,
  LegacyProjectsRoute: LegacyProjectsRoute,
  LegacySettingsRoute: LegacySettingsRoute,
  LegacyTeamsRoute: LegacyTeamsRoute,
  LegacyTemplatesRoute: LegacyTemplatesRoute,
  LegacyWebhooksRoute: LegacyWebhooksRoute,
  LegacyIndexRoute: LegacyIndexRoute,
}

const LegacyRouteWithChildren =
  LegacyRoute._addFileChildren(LegacyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  HealthzRoute: HealthzRoute,
  LegacyRoute: LegacyRouteWithChildren,
  ReadyzRoute: ReadyzRoute,
  ApiPublicJobsMediaRoute: ApiPublicJobsMediaRoute,
  ApiPublicWebhooksMetaWhatsappRoute: ApiPublicWebhooksMetaWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
