// This file is automatically generated. Do not edit it directly.
// Server-side Supabase clients with service role key - bypass RLS.
// Use these for trusted server operations only.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function requiredServerEnv() {
  const SUPABASE_URL = process.env['SUPABASE_URL'];
  const SUPABASE_SERVICE_ROLE_KEY = process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY };
}

function clientOptions(serviceRoleKey: string) {
  return {
    global: {
      fetch: createSupabaseFetch(serviceRoleKey),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  };
}

function createSupabaseAdminClient() {
  const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } = requiredServerEnv();
  return createClient<Database>(
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY,
    clientOptions(SUPABASE_SERVICE_ROLE_KEY),
  );
}

// Some backend runtime tables are installed by migrations after the checked-in
// generated Database type. This client deliberately uses PostgREST's runtime
// schema so those tables can be updated without weakening the typed client used
// everywhere else.
function createSupabaseRuntimeAdminClient() {
  const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } = requiredServerEnv();
  return createClient(
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY,
    clientOptions(SUPABASE_SERVICE_ROLE_KEY),
  );
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;
let _supabaseRuntimeAdmin: ReturnType<typeof createSupabaseRuntimeAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

// Runtime-schema variant for server-only operational tables that may be newer
// than src/integrations/supabase/types.ts. Keep its use narrow and explicit.
export const supabaseRuntimeAdmin = new Proxy(
  {} as ReturnType<typeof createSupabaseRuntimeAdminClient>,
  {
    get(_, prop, receiver) {
      if (!_supabaseRuntimeAdmin) _supabaseRuntimeAdmin = createSupabaseRuntimeAdminClient();
      return Reflect.get(_supabaseRuntimeAdmin, prop, receiver);
    },
  },
);
